### ISSUE TITLE
Spiel starten und beenden 🛫🏁-> Startbildschirm

### ISSUE THREAD

**Issue by LasseHuhn** [ABI2025/ST2-Highway_Havoc#14]
Erstellung eines Startbildschirms, welcher ansprechend in Pixelschrift zum Spielen einlädt.

[User Story]
#2

**Comment by Xadom** [comment]
Es gibt jetzt einen Startbildschirm, der über Tastatur- und/oder Mauseingabe gesteuert wird.
Es gibt die Möglichkeit das Spiel zu starten und zu beenden, sowie in die Einstellungen zu gehen.
